package org.multipaz.wallet.client.verification

import org.multipaz.cbor.DataItem
import org.multipaz.crypto.EcPrivateKey
import org.multipaz.mdoc.connectionmethod.MdocConnectionMethod
import org.multipaz.mdoc.nfc.MdocHandoverType
import org.multipaz.mdoc.request.DeviceRequest
import org.multipaz.mdoc.response.DeviceResponse
import org.multipaz.mdoc.transport.NfcHybridTransportStats
import kotlin.time.Duration

/**
 * Result and telemetry metrics from a mdoc proximity verification exchange.
 *
 * @property status Session termination status code sent by the holder, or `null` if the connection ended without status.
 * @property query The [Query] that was executed, or `null` if not configured.
 * @property deviceRequest The ISO/IEC 18013-5 [DeviceRequest] sent to the holder, or `null` if not sent.
 * @property deviceResponse The ISO/IEC 18013-5 [DeviceResponse] received from the holder, or `null` if no response was received.
 * @property sessionTranscript The CBOR [DataItem] encoding the session transcript used to derive session encryption keys.
 * @property eReaderKey Ephemeral private key generated by the reader for session encryption.
 * @property nfcHandoverType The NFC handover type used during engagement (e.g. [MdocHandoverType.V2_HANDOVER]), or `null` if NFC was not used.
 * @property durationNfcTapToEngagement Time elapsed from initial NFC tap until device engagement was received, if available.
 * @property durationEngagementReceivedToRequestSent Time elapsed from receiving device engagement until the request was sent.
 * @property durationRequestSentToResponseReceived Time elapsed from sending the device request until receiving the response.
 * @property durationScanningTime Time spent scanning for holder transport connections, if applicable.
 * @property connectionMethod The [MdocConnectionMethod] negotiated and used for data transfer.
 * @property nfcHybridTransportStats Statistics and diagnostics for NFC hybrid transport, if used.
 */
data class ProximityReaderModelResult(
    val status: Long?,
    val query: Query?,
    val deviceRequest: DeviceRequest?,
    val deviceResponse: DeviceResponse?,
    val sessionTranscript: DataItem,
    val eReaderKey: EcPrivateKey,

    val nfcHandoverType: MdocHandoverType?,
    val durationNfcTapToEngagement: Duration?,
    val durationEngagementReceivedToRequestSent: Duration,
    val durationRequestSentToResponseReceived: Duration,
    val durationScanningTime: Duration?,
    val connectionMethod: MdocConnectionMethod,
    val nfcHybridTransportStats: NfcHybridTransportStats?
)
