package org.multipaz.wallet.client.verification

/**
 * Base class for format-specific document requests generated by a [DocumentQuery].
 *
 * Known subclasses include [IsoMdocRequest] for ISO/IEC 18013-5 mdoc credentials and [SdJwtVcRequest] for
 * IETF SD-JWT VC credentials.
 */
sealed class Request
