package org.multipaz.wallet.client

import org.multipaz.presentment.CredentialPresentmentData
import org.multipaz.presentment.CredentialPresentmentSelection
import org.multipaz.request.Requester
import org.multipaz.util.Logger

private const val TAG = "PreconsentUtil"

/**
 * Evaluates whether any pre-consent settings apply to a given [CredentialPresentmentData] request,
 * optionally rewriting domains in the resulting selection.
 *
 * This function iterates through all possible selections generated by [getAllSelections]. For each
 * selection, it checks the [Document.preconsentSetting] of the documents involved in the matches.
 * The selection is considered approved if all its matches satisfy their respective pre-consent
 * settings. The settings can mandate consent unconditionally, waive it entirely, or base it on the
 * sensitivity of the requested data or the verified identity of the requester.
 *
 * If a selection is approved, the function attempts to rewrite the domain of each credential in the
 * selection using the provided [domainRewriter]. If rewriting fails for any credential (i.e., a
 * credential with the new domain doesn't exist in the document), the selection is discarded and
 * the function evaluates the next one. When multiple credentials exist for a given domain, the one
 * with the lowest usage count is selected.
 *
 * @receiver the [CredentialPresentmentData] containing the request and possible selections.
 * @param requester the [Requester] attempting to access the credentials, used to evaluate identity-based
 *                  pre-consent rules.
 * @param domainRewriter a function that takes the current domain of a credential and returns the new
 *                       domain it should be mapped to. Defaults to returning the same domain.
 * @return the first [CredentialPresentmentSelection] that satisfies all pre-consent rules and
 *         domain rewriting, or `null` if no such selection exists.
 */
suspend fun CredentialPresentmentData.checkPreconsent(
    requester: Requester,
    domainRewriter: (domain: String) -> String = { domain -> domain  }
): CredentialPresentmentSelection? {
    val selections = getAllSelections()
    checkSelection@ for (selection in selections) {
        for (match in selection.matches) {
            match.credential.document.preconsentSetting?.let { preconsentSetting ->
                when (preconsentSetting) {
                    DocumentPreconsentSetting.AlwaysRequireConsent -> {
                        // This selection doesn't work since this document always require consent
                        continue@checkSelection
                    }
                    DocumentPreconsentSetting.NeverRequireConsent -> {
                        // Have user's pre-consent for this document
                    }
                    is DocumentPreconsentSetting.RequestComplexityBased -> {
                        val requestComplexity = selection.getMaxSensitivity()
                        if (requestComplexity == null) {
                            // This selection doesn't work since the request contains unclassified claims
                            continue@checkSelection
                        }
                        if (requestComplexity > preconsentSetting.approvedSensitivity) {
                            // This selection doesn't work since the complexity exceeds the approved complexity
                            continue@checkSelection
                        }
                        // The request satisfies the approved sensitivity
                    }
                    is DocumentPreconsentSetting.ReaderIdentityBased -> {
                        val requestComplexity = selection.getMaxSensitivity()
                        
                        val certChain = requester.certChain?.certificates
                        if (certChain.isNullOrEmpty()) {
                            // This selection doesn't work since the requester chain is missing
                            continue@checkSelection
                        }

                        val isApproved = preconsentSetting.approvedReaders.any { approvedReader ->
                            val complexityOk = if (approvedReader.approvedSensitivity == null) {
                                true
                            } else {
                                requestComplexity != null && requestComplexity <= approvedReader.approvedSensitivity
                            }
                            
                            if (!complexityOk) {
                                return@any false
                            }

                            // 1. Direct match by public key
                            if (certChain.any { it.ecPublicKey == approvedReader.certificate.ecPublicKey }) {
                                return@any true
                            }

                            // 2. Chain match by AKI/SKI
                            val approvedSki = approvedReader.certificate.subjectKeyIdentifier
                            if (approvedSki != null) {
                                if (certChain.any { it.authorityKeyIdentifier?.contentEquals(approvedSki) == true }) {
                                    return@any true
                                }
                            }

                            false
                        }
                        
                        if (!isApproved) {
                            // This selection doesn't work since the requester is not approved
                            continue@checkSelection
                        }
                    }
                }
            } ?: continue@checkSelection
        }

        // If we get to here, all documents are go for pre-consent for this selection. Now we just
        // need to remap the domains in selection according to domainRewriter. This can fail if
        // the domainRewriter function maps to a domain where there are no credentials in the domain.
        //
        // If this fails we continue trying other selections.
        
        val newMatches = mutableListOf<org.multipaz.presentment.CredentialPresentmentSetOptionMemberMatch>()
        var remappingFailed = false
        for (match in selection.matches) {
            val oldDomain = match.credential.domain
            val newDomain = domainRewriter(oldDomain)
            
            val newCredential = match.credential.document.getCredentials()
                .filter { it.domain == newDomain }
                .minByOrNull { it.usageCount }
            
            if (newCredential == null) {
                remappingFailed = true
                break
            }
            newMatches.add(match.copy(credential = newCredential))
        }

        if (remappingFailed) {
            continue@checkSelection
        }

        return selection.copy(matches = newMatches)
    }
    return null
}